### ISSUE TITLE
Consider Typescript Parser

### ISSUE THREAD

**Issue by panoply** [marcoroth/stimulus-parser#15]
Acorn might not be the best choice here. While slower and harder to reason with, the TypeScript parser might be the easier route to take in order to obtain lexical context of each controller.

Referencing https://github.com/marcoroth/stimulus-parser/issues/9

**Comment by marcoroth** [comment]
I would be fine with that, I think Acorn was the "best" solution available when in started the project in 2020. 

Before releasing it last month I was also looking at https://github.com/unjs/magicast, but figured I'd leave it for the initial version, since the most basic version of the LSP was already working just fine with Acorn. 

But now that we have more requirements we should consider it.

**Comment by marcoroth** [comment]
Maybe we could also depend on the `@typescript-eslint/parser` or `@typescript-eslint/typescript-estree` package.

https://typescript-eslint.io/packages/parser/
https://typescript-eslint.io/packages/typescript-estree/

**Comment by marcoroth** [comment]
This should be resolved via #49
